### PR TITLE
[US-69][US-72][US-73] Fixed the issue with creation of new  multi-sig on web and fixed wall…

### PR DESCRIPTION
**Pull request by ashishnair-zil**
1.) Create a new multi-sig wallet with a standard format which is similar to [ide.zilliqa.com](http://ide.zilliqa.com/).
2.) Added support for both version of multi-sig wallet
3.) Handle few minor issues.
4.) Code optimization.
5.) Commented the code for ZRC2 support on the frontend as we will have to create a new smart contract which supports zrc2 managment.

Jira Ticket no:
https://zilliqa-jira.atlassian.net/browse/US-69
https://zilliqa-jira.atlassian.net/browse/US-72
https://zilliqa-jira.atlassian.net/browse/US-73

### CODE REVIEW

**Comment by inamirandaz** [comment]
>  2.) Added support for both version of multi-sig wallet

@ashishnair-zil to support both versions, should the transitions `SubmitTransaction` and `SubmitNativeTransaction` be supported depending on the loaded contract? I only see `SubmitNativeTransaction`

**Comment by inamirandaz** [comment]
This is probably for later, there are a few places where the multisig contract is defined:
- walletdefinition.js, contract.scilla and in test-ini.json. This should be cleaned up later.

**Comment by ashishnair-zil** [comment]
> 
We are not using SubmitNativeTransaction. We only use SubmitTransaction, so i have updated the code according to SubmitTransaction. I don't know which branch we are running on https://multisig-test.web.app/ but the smartcontract deployed from https://multisig-test.web.app/ and https://multisig.zilliqa.com/ both does not have SubmitNativeTransaction transition.

**Comment by ashishnair-zil** [comment]
> This is probably for later, there are a few places where the multisig contract is defined:
> 
> * walletdefinition.js, contract.scilla and in test-ini.json. This should be cleaned up later.

deleted these files

**Review by inamirandaz — APPROVED** [review]

**Pull request merged**
